### PR TITLE
Java bindings

### PR DESCRIPTION
**Pull request by spazzymoto**
Added bindings for Java.

Opening as a draft as i need to work on the build scripts still.

### CODE REVIEW

**Comment by mlangkabel** [comment]
Hi @spazzymoto, first of all, thank you very much for your contribution! Great work so far!

Right now I am reviewing your changes and in that process I'm also testing everything on Windows. I'd like to have the whole pipeline running before looking at the code in depth.

So when running the example I'm still encountering these issues:
* Of course I need to compile the example, before I can run it. I think this line is missing in the readme of the example:
```
javac -cp SourcetrailDB.jar example.java
```
* Before I can do that, I need to copy the `SourcetrailDB.jar` file to the example folder. I think this step is also missing. Or did you do it differently?
* When executing the example via `java -Djava.library.path=. example ...`, I get a the following error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/sourcetrail/sourcetraildb
        at example.main(example.java:44)
Caused by: java.lang.ClassNotFoundException: com.sourcetrail.sourcetraildb
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 1 more
```
And when I inspect the `SourcetrailDB.jar` with `jar tf SourcetrailDB.jar` I get:
```
META-INF/
META-INF/MANIFEST.MF
com/sourcetrail/DefinitionKind.class
com/sourcetrail/ReferenceKind.class
com/sourcetrail/SymbolKind.class
com/sourcetrail/sourcetraildb.class
com/sourcetrail/sourcetraildbJNI.class
```

**Comment by spazzymoto** [comment]
Hey @mlangkabel,

Sorry for the delayed response, i shall take a look at those asap and get them sorted. Sorry about that.

**Comment by spazzymoto** [comment]
Hey @mlangkabel ,

Please let me know if that works :)

**Comment by mlangkabel** [comment]
@spazzymoto, it worked! I followed the instructions as specified in the readme files and got everything running. I also reviewed all of your changes. Two **optional** points that you can address if you want before I accept this pull request:
* On Windows the scripts copy `_sourcetraildb.dll` and `SourcetrailDB.jar`, as well as `example.java` to the `build` (CMAKE_BINARY_DIR) folder. Maybe we should change the readme of the example to run everything in the `build` folder instead of using the `examples` folder. But if you want, I can do that after accepting the PR.
* You may want to add your name to the `AUTHORS.txt` file ;)

**Comment by mlangkabel** [comment]
Ok, I guess I will merge this one now. If you don't mind being mentioned in the AUTHORS file, feel free to hand in another pull request for that or just reply here and I will add you.

**Pull request merged**
